---
title: "TSE_2_Schultz"
author: "Robert Schultz"
date: "2/15/2022"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(xml2)
library(rvest)
library(survey)
library(magrittr)
library(scales)
library(ggpubr)
library(dplyr)
library(sjPlot)
library(stargazer)
```

```{r cars}
# Pull in Pulse ACS Data
# Pull in ACS Weighting Data
library(haven)
pulse2022_puf_41 <- read_sas("~/Downloads/HPS_Week41_PUF_SAS/pulse2022_puf_41.sas7bdat", 
    NULL)
pulse2022_repwgt_puf_41 <- read_sas("Downloads/HPS_Week41_PUF_SAS/pulse2022_repwgt_puf_41.sas7bdat", 
    NULL)

```

```{r}
# Rename Data sets
Pulse <- pulse2022_puf_41
Weight <- pulse2022_repwgt_puf_41
head(Weight)
# First column is Week (41)
```
```{r}
# Create new data frame w/ selected variables
Pulse2 <- data.frame(Pulse$EGENID_BIRTH, Pulse$GENID_DESCRIBE, Pulse$DOWN, Pulse$ANXIOUS, Pulse$RRACE, Pulse$SCRAM, Pulse$PWEIGHT, Pulse$TBIRTH_YEAR, Pulse$SCRAM)
colnames(Pulse2)
```

```{r}
# Create new variable for Age (2021 - Year Born)
summary(Pulse2$Pulse.TBIRTH_YEAR)
Age.Center <-mean(Pulse2$Pulse.TBIRTH_YEAR)
Center.AGE <- (Pulse2$Pulse.TBIRTH_YEAR - Age.Center)
Pulse2$Center.AGE <- (Pulse2$Pulse.TBIRTH_YEAR - Age.Center)
hist(Pulse2$Center.AGE)
```

```{r}
names(Pulse2)[names(Pulse2) == "Pulse.EGENID_BIRTH"] <- "Gender_Birth"
names(Pulse2)[names(Pulse2) == "Pulse.GENID_DESCRIBE"] <- "Gender_Identity"
names(Pulse2)[names(Pulse2) == "Pulse.DOWN"] <- "Depression"
names(Pulse2)[names(Pulse2) == "Pulse.ANXIOUS"] <- "Anxiety"
names(Pulse2)[names(Pulse2) == "Pulse.RRACE"] <- "Race"
names(Pulse2)[names(Pulse2) == "Center.AGE"] <- "Age"
names(Pulse2)[names(Pulse2) == "Pulse.SCRAM"] <- "SCRAM"
names(Pulse2)[names(Pulse2) == "Pulse.PWEIGHT"] <- "PWEIGHT"
```

```{r}
#Combine Pulse Dataframe with Weighting dataframe
require(dplyr)
full_join <- full_join(Pulse2, Weight,by="SCRAM")
```

```{r}
#Rename Full_join (Pulse and Weight Data) as Pulse2
Pulse2 <- full_join
```

```{r}
#Re-code -99 as Non Response (N/A's)
Pulse2 <- Pulse2 %>% mutate(Gender_Identity = replace(Gender_Identity, Gender_Identity == "-99", NA))
Pulse2 <- Pulse2 %>% mutate(Depression = replace(Depression, Depression == "-99", NA))
Pulse2 <- Pulse2 %>% mutate(Anxiety = replace(Anxiety, Anxiety == "-99", NA))
```

```{r}
# Remove all N/A's from data file
na.omit(Pulse2)
Pulse2 <- Pulse2[complete.cases(Pulse2), ]
```

```{r}
Pulse2$Gender_Birth[Pulse2$Gender_Birth == "1"] <- "Male"
Pulse2$Gender_Birth[Pulse2$Gender_Birth == "2"] <- "Female"

Pulse2$Gender_Identity[Pulse2$Gender_Identity == "1"] <- "Male"
Pulse2$Gender_Identity[Pulse2$Gender_Identity == "2"] <- "Female"
Pulse2$Gender_Identity[Pulse2$Gender_Identity == "3"] <- "Transgender"
Pulse2$Gender_Identity[Pulse2$Gender_Identity == "4"] <- "Other"

Pulse2$Race[Pulse2$Race == "1"] <- "White"
Pulse2$Race[Pulse2$Race == "2"] <- "African American"
Pulse2$Race[Pulse2$Race == "3"] <- "Asian"
Pulse2$Race[Pulse2$Race == "4"] <- "Other"
```

```{r}
# SDR Sample Design
## 4 / 80
##Formal weight argument 
Design <- svrepdesign(data = Pulse2, repweights = Pulse2[12:91],
                      type = "successive-difference",
                      weights = ~PWEIGHT, combined.weights = TRUE, fpc = NULL, 
                      fpctype = NULL)
print(Design)
```

```{r}
#Table to see where gender identity report sex at birth by %%
source("http://pcwww.liv.ac.uk/~william/R/crosstab.r")
library(questionr)
require(questionr)

table3 <- prop.table(wtd.table(Pulse2$Gender_Identity, Pulse2$Gender_Birth, weights =Pulse2$PWEIGHT), margin = 1)
print(table3)
```

```{r}
require(questionr)

addmargins(wtd.table(Pulse2$Gender_Identity, Pulse2$Gender_Birth, weights =Pulse2$PWEIGHT), margin = 1)

```

```{r}
addmargins(table(Pulse2$Gender_Identity, Pulse2$Gender_Birth))
```

```{r}
prop.table(table(Pulse2$Gender_Identity, Pulse2$Gender_Birth), margin = 1)
```

```{r}
svymean(~Gender_Birth, design=Design, na.rm=T)
svymean(~Gender_Identity, design=Design, na.rm = T)
svymean(~Depression, design=Design, na.rm=T)
svymean(~Anxiety, design=Design, na.rm=T)
svymean(~Age, design=Design, na.rm=T)
svymean(~Race, design=Design, na.rm=T)
```

```{r}
#Ordinal Model Anxiety with Gender Identity options
require(survey)
Pulse2$Anxiety <- factor(Pulse2$Anxiety)
Pulse2$Gender_Identity <- factor(Pulse2$Gender_Identity)
Pulse2$Race <- factor(Pulse2$Race)

Pulse2$Gender_Identity <- relevel(Pulse2$Gender_Identity, ref = "Male")
Pulse2$Race <- relevel(Pulse2$Race, ref = "White")
                              
model3 <-svyolr(as.factor(Anxiety) ~ Gender_Identity + Age + Race, design = Design)
summary(model3)
```

```{r}
coef(model3)
exp(coef(model3))
exp(model3$zeta)
```

```{r}
library(sjPlot)
tab_model(model3,show.se = T, title = "Table 1")
```

```{r}
#Ordinal Model Anxiety with Gender at birth options
Pulse2$Anxiety <- factor(Pulse2$Anxiety)
Pulse2$Gender_Birth <- factor(Pulse2$Gender_Birth)
Pulse2$Race <- factor(Pulse2$Race)

Pulse2$Race <- relevel(Pulse2$Race, ref = "White")
Pulse2$Gender_Birth <- relevel(Pulse2$Gender_Birth, ref = "Male")
                              
dclus1<-svydesign(id=~0, weights=~PWEIGHT, data=Pulse2)
model4 <-svyolr(Anxiety ~ Gender_Birth + Age + Race, design=dclus1)
summary(model4)
```

```{r}
# Pull out coefficients 
coef(model4)
exp(coef(model4))
exp(model4$zeta)
```

```{r}
library(sjPlot)
tab_model(model4,show.se = T, title = "Table 2")
```

```{r}
#Ordinal Model Depression with Gender identity
Pulse2$Depression <- factor(Pulse2$Depression)
Pulse2$Gender_Identity <- factor(Pulse2$Gender_Identity)
Pulse2$Race <- factor(Pulse2$Race)

Pulse2$Gender_Identity <- relevel(Pulse2$Gender_Identity, ref = "Male")
Pulse2$Race <- relevel(Pulse2$Race, ref = "White")
                              
dclus1<-svydesign(id=~0, weights=~PWEIGHT, data=Pulse2)
model5 <-svyolr(Depression ~ Gender_Identity + Age + Race, design=dclus1)
summary(model5)
```

```{r}
# Pull out coefficients 
coef(model5)
exp(coef(model5))
exp(model5$zeta)
```

```{r}
library(sjPlot)
tab_model(model5,show.se = T, title = "Table 3")
```

```{r}
#Ordinal Model Depression with Gender at birth
Pulse2$Depression <- factor(Pulse2$Depression)
Pulse2$Gender_Birth <- factor(Pulse2$Gender_Birth)
Pulse2$Race <- factor(Pulse2$Race)

Pulse2$Gender_Identity <- relevel(Pulse2$Gender_Birth, ref = "Male")
Pulse2$Race <- relevel(Pulse2$Race, ref = "White")
                              
dclus1<-svydesign(id=~0, weights=~PWEIGHT, data=Pulse2)
model6 <-svyolr(Depression ~ Gender_Birth + Age + Race, design=dclus1)
summary(model6)
```

```{r}
# Pull out coefficients 
coef(model6)
exp(coef(model6))
exp(model6$zeta)
```

```{r}
library(sjPlot)
tab_model(model6,show.se = T, title = "Table 4")
```


```{r}
library(ggplot2)
plot_model(model3)
plot_model(model4)
```
```{r}
library(ggplot2)
plot_model(model5)
plot_model(model6)
```

```{r}
citation("sampling")
citation("survey")
citation("ggplot2")
RStudio.Version()
R.version
```

```{r}
barplot(table(Pulse2$Pulse.EGENID_BIRTH, Pulse2$Pulse.ANXIOUS), beside = T, 
        cex.names = 0.7, legend.text = c("Male","Female"),
        names.arg=c("Not at all","Several days", "More than half the days","Nearly Every Day"),
        args.legend = list(x="topright", y=25, cex=0.8),
         main="Anxiety Levels by Gender Assigned at Birth",
        xlab="Frequency of anxiety over previous 2 weeks",
        ylab="Count",
        col = c("light blue", "blue"))
```

```{r}
barplot(table(Pulse2$Pulse.EGENID_BIRTH, Pulse2$Pulse.DOWN), beside = T, 
        cex.names = 0.7, legend.text = c("Male","Female"),
        names.arg=c("Not at all","Several days", "More than half the days","Nearly Every Day"),
        args.legend = list(x="topright", y=25, cex=0.8),
         main="Depression Levels by Gender Assigned at Birth",
        xlab="Frequency of feeling depressed over previous 2 weeks",
        ylab="Count",
        col = c("light blue", "blue"))
```

```{r}
library(stargazer)
set_theme(geom.label.color = "Blue", geom.label.size = 3)
plot_grpfrq(Pulse2$Gender_Birth, Pulse2$Gender_Identity, expand.grid = TRUE , title = "Gender at Birth by Gender Identity", axis.titles = "Gender at Birth",axis.labels = c("Male","Female"), legend.title = "Current Gender Identity", legend.labels = c("Male","Female","Transgender","None of the Above"))
```

```{r}
library(stargazer)
set_theme(geom.label.color = "blue", geom.label.size = 3)
plot_frq(Pulse2$Gender_Birth, type = "bar", title = "Gender assiged at birth",axis.title = "Gender at Birth", axis.labels = c("Male", "Female"))  + set_theme(geom.label.color = "blue", geom.label.size = 3) 
```

```{r}
svymean(~Gender_Birth, design=dclus1, na.rm=T)
svymean(~Gender_Identity, design=dclus1, na.rm = T)
svymean(~Depression, design=dclus1, na.rm=T)
svymean(~Anxiety, design=dclus1, na.rm=T)
svymean(~Age, design=dclus1, na.rm=T)
svymean(~Race, design=dclus1, na.rm=T)
```

